Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.provision "shell", path: "install_django.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
  end
end
